### ISSUE TITLE
Simplify oAuth configuration for sample app's SDK.

### ISSUE THREAD

**Issue by ctg-api** [ciscospark/spark-js-sdk#125]
Opened an issue as requested on this topic. Right now, for a developer to publish their own instance of example app's, they must edit the oAuth details in /packages/example-phone/src/scripts/modules/redux-spark/spark.js.

Can this be simplified? Or alternatively, document the difference between hardcoded oAuth, and a developers own instance (including Spark App Scope requirements)?

**Comment by ianwremmel** [comment]
example-phone is no longer in the sdk
