### ISSUE TITLE
Add support to set environment variables when running gruntfile.concurrent.js on Windows command line

### ISSUE THREAD

**Issue by ctg-api** [ciscospark/spark-js-sdk#126]
As it exists today, gruntfile.concurrent.js contains commands to set environment variables that will NOT work on windows. Can we add a command that will work on both Windows and MAC platforms? 

In the meantime, for windows, the developer will need to change line 145 and 151:

command: 'PACKAGE=' + packageName + ' grunt --gruntfile Gruntfile.package.js --no-color build'
command: 'PACKAGE=' + packageName + ' grunt --gruntfile Gruntfile.package.js --no-color test'
    to:
command: 'SET PACKAGE=' + packageName + '&grunt --gruntfile Gruntfile.package.js --no-color build'
command: 'SET PACKAGE=' + packageName + '&grunt --gruntfile Gruntfile.package.js --no-color test'

And also, the build command:

`PACKAGE=example-phone npm run grunt:package -- webpack:build`
should be changed to two separate commands:
`SET PACKAGE=example-phone`
and,
`npm run grunt:package -- webpack:build`

Or alternatively:
`SET PACKAGE=example-phone&npm run grunt:package -- webpack:build`

**Comment by ianwremmel** [comment]
example-phone is no longer in the sdk
