### ISSUE TITLE
No form-data support for message attachments

### ISSUE THREAD

**Issue by misobytes** [ciscospark/spark-js-sdk#162]
The SDK only supports a `messages.create` containing attachments via the `files` array property. That property only allows for an array of urls.

I cannot use the SDK to post form-data with an actual file/buffer. I would need to use the raw Spark API to do that.

It would be cool if the SDK provided an interface for this natively. :)

**Comment by ianwremmel** [comment]
yea, that feature slipped by. In the short term, you can use spark.request to to upload files using the api; I'd like to think i'll have time to tackle this issue sometime next week, or I'm happy to take PRs :)
