### ISSUE TITLE
Issue building the sdk for browser

### ISSUE THREAD

**Issue by xth1** [ciscospark/spark-js-sdk#229]
When I run npm run build I got this message Message:
   Warning: packages/spark-core/src/index.js: `MemoryStoreAdapter` has already been exported. Exported identifiers must be unique. (43:2) Use --force to continue.

I had to remove this line in order to successfully build it: https://github.com/ciscospark/spark-js-sdk/blob/master/packages/spark-core/src/index.js#L13

Node version: 6.4.0

**Comment by ianwremmel** [comment]
Yep. There's a bug in master. It should be fixed soon but please note that

1. You *really* want to install from npm, not github.
2. If you decide to clone from github rather than installing from npm, you should checkout the latest stable version (which, unfortunately is not tagged, but is available at c49ca68f5a88c2fc93b98e666ca122fad637d96a).

**Comment by ianwremmel** [comment]
I'll update the docs as soon as I can to explain how to build from npm. 

If you're using browserify or webpack already, 

1. run `npm install --save ciscospark`

2. Set the `CISCOSPARK_CLIENT_ID`, `CISCOSPARK_CLIENT_SECRET`, `CISCOSPARK_SCOPE`, and `CISCOSPARK_REDIRECT_URI` environment variables

3. Include the sdk in your project with

```javascript
var CiscoSpark = require('ciscospark');
```

If you're not using browserify and want to expose the sdk as a window global, then the following should do it (again, with the `CISCOSPARK_*` environment variables set:

```
npm install ciscospark
npm install -g browserify
echo "window.ciscospark = require(`ciscospark`)" > ./index.js
browserify index.js > bundle.js
```

From there, include bundle.js via a script tag.

**Comment by xth1** [comment]
Thank you, it worked.

**Comment by ianwremmel** [comment]
closing. these build steps have been added to the published documentation
