### ISSUE TITLE
The event "change:authorization" isn't working

### ISSUE THREAD

**Issue by xth1** [ciscospark/spark-js-sdk#240]
As the documentation pointed out, I tried to use this event to detect when the user was authorized but it doesn't seems to have support in the SDK.

```
    ciscospark.on('change:authorization', function() {
        console.debug("changeAuthorization:", ciscospark.credentials);
        localStorage.setItem('credentials', JSON.stringify(ciscospark.credentials));
    });

```

Using Ciscospark 0.6.9 installed from npm and built for browsers.

**Comment by ianwremmel** [comment]
I do apologize, that's a mistake in the documentation. Please use

```
ciscospark.credentials.on('change:credentials')
```

The upcoming 0.7.0 release will help simplify a lot of these issues once it stabilizes.

**Comment by xth1** [comment]
Thank you, no problem.

**Comment by ianwremmel** [comment]
closing this. as of the 0.7.0 release, caching is now handled by the sdk.
