### ISSUE TITLE
Unable to use plugin-conversation in webpack environment

### ISSUE THREAD

**Issue by adamweeks** [ciscospark/spark-js-sdk#257]
Since the addition of the 'mime' module in the `plugin-conversation`, additional webpack configuration is required to use it. I'm not sure if this is wanted or not. 

The additional webpack configuration is:
```
node: {
  fs: 'empty'
}
```
Because mime uses node's fs module to load files.

As well as 
```
{
  test: /\.json$/,
  loader: 'url'
},
```
because mime loads a json file.

**Comment by ianwremmel** [comment]
yea, that's definitely a bug. I think I meant to use https://www.npmjs.com/package/mime-types instead but forgot which one was which. It should be a trivial PR to swap them out, otherwise I can look next week.

**Comment by adamweeks** [comment]
ah, will look into that now!
