### ISSUE TITLE
Question on init and authenticate methods

### ISSUE THREAD

**Issue by carlosescalanteeloyalty** [ciscospark/spark-js-sdk#265]
I have something like this in the javascript file that gets executed in the browser:

`var authInfo = {
      'CISCOSPARK_CLIENT_ID': 'Ce52f0ae3fc406dddd2868ecae07a5a8ea6a45c2…',
      'CISCOSPARK_CLIENT_SECRET': 'd470edf7e4165a485198ffb8c75f1f2487d6d…',
      'CISCOSPARK_SCOPE': "spark:people_read spark:rooms_read spark:rooms_write spark:memberships_read spark:memb…",
      'CISCOSPARK_REDIRECT_URI': 'http://127.0.0.1:3000/rooms'
    }`

I use it to get an access token, like this:

`xhttp.open('POST', 'https://api.ciscospark.com/v1/access_token', true); // Initialize the HTTP request object for POST to the access token URL
                // Build the HTML form request body
                var body = 'grant_type=authorization_code&'+  // This is an OAuth2 Authorization Code request
                                'redirect_uri='+encodeURIComponent(appRedirectUri)+'&'+ // Same custom app Redirect URI`

…

And that works fine, I then send that token to the backend, which does something like this:

`var token = req.params.token || null;
   request
      .get('https://api.ciscospark.com/v1/rooms')
      .set('Authorization', 'Bearer ' + token)`

Anyway back to the question…. If I have something like:

`var spark = require('ciscospark');

spark.init({
      credentials: {
        authorization: {
          access_token: 'ZTYzMGMwY2ItOGY2MS00Njg3LThmNTktNDQ3NjAxM2RiZm....', // I got this one from https://developer.ciscospark.com/
          refresh_token: process.env.CISCOSPARK_REFRESH_TOKEN // no idea…
        }
      }
    })

 spark.authenticate();` // what is this exactly for? / how to use it?

I don’t really know how to use the init nor the authenticate methods that are part of the ciscospark npm package.

Can you shed some light in here? Are these two approaches interchangeable?

**Comment by ianwremmel** [comment]
ok, i see a couple things going on here.

First `xhttp.open('POST', 'https://api.ciscospark.com/v1/access_token', true);`, isn't generally going to work. It'll work iff the user has logged in via a UI in the last two hours and, therefore, has a cookie set on the login site. In the general case, that's going to end with an error.

At the moment, authorizing a backend app is a bit hairier than I'd like it be (I hope to release a passport plugin at some point in the not-too-distant future, but it's not a priority just yet). That said, you'll probably want a route handler something like the following to handle your oauth redirect.

```javascript
app.get(`/oauth/redirect`, (req, res) => {
});
```

**Comment by carlosescalanteeloyalty** [comment]
But it does work! I have not yet received an error like the one you’re describing.

I guess I will continue to use this approach for now. I was just curious if I could authorize differently.


Thanks!

**Comment by ianwremmel** [comment]
ok, i see a couple things going on here.

First `xhttp.open('POST', 'https://api.ciscospark.com/v1/access_token', true);`, isn't generally going to work. It'll work iff the user has logged in via a UI in the last two hours and, therefore, has a cookie set on the login site. In the general case, that's going to end with an error.

At the moment, authorizing a backend app is a bit hairier than I'd like it be (I hope to release a passport plugin at some point in the not-too-distant future, but it's not a priority just yet). That said, you'll probably want a route handler something like the following to handle your oauth redirect. (I'm just using assert to demostrate data shapes, you generally won't need that level of strictness).

```javascript
const ciscospark = require(`ciscospark`);
const assert = require(`assert);
app.get(`/oauth/redirect`, (req, res) => {
  assert(req.params.code);
  req.spark = ciscospark.init({});
  req.spark.authorize(req.params)
    .then(() => {
      // Do something here to either cache spark.credentials.authorization
      // then redirect your user-agent to a post-login page
    });
});
```

then, on subsequent requests, you'll do something like
```javascript
app.use((req, res, next) => {
  if (req.userIsLoggedIn) {
    getCachedAuthorization(req.loggedInUser, function(err, auth) => {
      if (err) {
        return next(err);
      }
      req.spark = ciscospark.init({
        credentials: auth
      });
      next();
  });
});
```

This assumes you've set the `CISCOSPARK_CLIENT_ID`, `CISCOSPARK_CLIENT_ID`, `CISCOSPARK_SCOPE`, and `CISCOSPARK_REDIRECT_URI` environment variables on your server side. 

On the client side, you can roll your own code to kick off the oauth flow, or you can use `ciscospark` to something like:

```html
<script>
document.getElementById(`btn-login`).addEventHandler(`click`, () => {
  ciscospark.authorize();
});
</script>
```
again, this assumes you've built ciscospark with the CISCOSPARK environment variables set.

**Comment by ianwremmel** [comment]
sorry about that, i accidentally posted the first paragraph, then deleted that post to try to finish it before you read it :)


Just to verify, xhttp is a library for simplifying XMLHttpRequest, right? I'm pretty sure getting an auth code that way will only work if you have recently entered your username and password (I think the cookie last two hours). If you try it in an incognito window, I think you'll find yourself in a weird scenario: the xhr won't fail, but you also won't get a code back.
