### ISSUE TITLE
Example-phone build - browserify failing. 

### ISSUE THREAD

**Issue by ctg-api** [ciscospark/spark-js-sdk#278]
user-mac:spark-js-sdk user$ browserify --standalone ciscospark packages/ciscospark > bundle.js

Error: Cannot find module './dist' from '/Users/<user>/Desktop/ALTO/spark-js-sdk/packages/ciscospark'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

OS X El Capitan. Version 10.11.6.

**Comment by ianwremmel** [comment]
it looks like you probably didn't build the modules before trying to bundle them. please try the instructions here: https://www.npmjs.com/package/ciscospark

**Comment by ctg-api** [comment]
Yes, I had used an older version of the commands. Thanks
