### ISSUE TITLE
webhooks.list() in does not return the webhooks in the ciscospark package

### ISSUE THREAD

**Issue by andrewholsted** [ciscospark/spark-js-sdk#319]
In the webhooks plugin of the ciscospark package, the list method returns a new page instance which is different than the other methods in the file. 

Here's the [line](https://github.com/ciscospark/spark-js-sdk/blob/4d0529e7e46e0dbca0f766db183a8cdb9647239e/packages/ciscospark/src/plugins/webhooks.js#L144) in question. 

I think returning `res.body.items || res.body` would work. I'm not familiar with how the packages integrate with this main repo or if this is even the correct place to raise this issue. Happy to submit a pull request if I'm on the right track.

**Comment by ianwremmel** [comment]
That's how all of the list functions work. Page objects can be iterated via for...of or you can use page.items.forEach

**Comment by andrewholsted** [comment]
ahhh. I see. When I tried to console.log() the page object, it looked empty but page.items is definitely there. I guess it's some kind of prototype property? It threw me for a loop that the response was structurally different than other methods. Thanks for the clarification!
