### ISSUE TITLE
Spark authorization page has duplicate icons

### ISSUE THREAD

**Issue by Popl7** [ciscospark/spark-js-sdk#330]
On the page shown after a Spark login, requesting the users permissions, both the Company log and the Spark logo are shown:

![screen shot 2016-11-16 at 11 40 24](https://cloud.githubusercontent.com/assets/4224518/20344146/d4937bc8-abf1-11e6-87df-ab954768cdc5.png)

**Comment by ianwremmel** [comment]
Can you email this issue to the folks at devsupport@ciscospark.com? (I've already told them about it, but it'll be a lot easier to loop you in to the resolution if the email comes from your email address).

**Comment by Popl7** [comment]
Thx.
I have sent them an email.

**Comment by ianwremmel** [comment]
Closing this ticket as this is a non-sdk issue being pursued via an alternate support channel.
