### ISSUE TITLE
Unable to post images to spark rooms

### ISSUE THREAD

**Issue by wheller** [ciscospark/spark-js-sdk#394]
Our team has run into some issues when using the spark-js-sdk in conjunction with hubot. 

There appears to be a small error preventing us from posting images at all. This seems to be coming from a line that is binding the return of a function, when it should be binding the function to "this".
[src/client/services/conversation/share-activity/share-activity.js line 33]

Further, when we are able to post images, the state object saves the spaceURL for the first room encountered. This makes it impossible to post an image to a second room in the same session.
[src/client/services/conversation/share-activity/share-activity-base.js  Lines 146 & 147]

**Comment by ianwremmel** [comment]
Hi @wheller, can you share the code in your hubot that's causing the problem? The `target` should be the conversation object that the Activity will shortly be posted into, so i'm not clear how your bot would be having the problem that you're trying to fix. Without caching the space urls on the target, it's like you're bot could get rate limited by requesting them all the time.

Further, you should know that code in the sdk's `src` directory is deprecated and will be removed in the next few months. Ideally, the package you're looking for is `ciscospark` on npm and stored at packages/ciscospark. `ciscospark` is the sdk for our public api defined at developers.ciscospark.com

That said, if webhooks aren't ideal for your hubot, take inspiration from `packages/recipe-private-web-client` for using the code that's replacing the `src` directory in your bot. The web client recipe is close to what you need, but loads in a few things that are browser specific.

Of course, ciscospark is the only package that has a reasonably solid contract. If you're not using the packages that point at the developer api, be prepared for poorly communicated breaking changes.

**Comment by ianwremmel** [comment]
Closing this and #395 due to lack of activity. Please reopen if appropriate.
