### ISSUE TITLE
Plugins cannot replace standard ones (e.g. plugin-logger)

### ISSUE THREAD

**Issue by hagemt** [ciscospark/spark-js-sdk#441]
In some scenarios, we'd like to replace the `this.spark.logger` but run into some trouble:

Calling `registerPlugin('logger', ..., { replace: true, ... })` works as expected, but:

Doing so *before* `require('ciscospark')` is "required", since the import constructs an instance.
(registering plugins after instances are created is bad, unless you can guarantee they're unused)
Doing so *after* `require('ciscospark')` will throw an Error if `NODE_ENV !== 'production'`.

IMHO, I think the `interceptors` mechanism is sufficient for adding hooks. (enables quite a bit)
But AFAIK, this doesn't enable us to capture and redirect everything that the SDK would log.

Thanks.

**Comment by hagemt** [comment]
FTR, we hacked around this issue by explicitly registering the "stock" `logger` plugin first, then replacing it with our own, which works for us since we never use the default instance.

**Comment by joeyyin123** [comment]
@hagemt Does the issue still persist on your side? Thanks.

**Comment by hagemt** [comment]
@joeyyin123; will close. Not sure if it was addressed, but the workaround (as above) was fine for us.
