### ISSUE TITLE
bundled JS Spark not working in Firefox. Does work in Chrome but bad quality

### ISSUE THREAD

**Issue by Popl7** [ciscospark/spark-js-sdk#50]
we are still working on our web implementation of Spark video calling.
In Chrome 52.0 we have an Angular2 app and a plain html page working with an bundled Spark JS file.
The video quality is bad.
With the Cisco demo app the video quality is fine.

With Firefox 48.0 both the Angular2 app and the plain html page won't work.
So right now the video quality is untestable.

The Firefox browser doesn't get all events and also complaints about the remoteMediaStreamUrl.

The spark.js is generated with:
export CISCOSPARK_CLIENT_ID=xxxxx
export CISCOSPARK_CLIENT_SECRET=xxxxx
export CISCOSPARK_SCOPE='spark:messages_write spark:rooms_read spark:teams_read spark:memberships_read spark:messages_read spark:rooms_write spark:people_read spark:team_memberships_write spark:team_memberships_read spark:teams_write spark:memberships_write'
export CISCOSPARK_REDIRECT_URI=http://localhost:5555/

npm install -g browserify
npm install -g uglify-js

npm install
npm run bootstrap
npm run build
browserify --standalone ciscospark packages/ciscospark > spark.js

**Comment by Popl7** [comment]
the html page looks like this:


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cisco Spark</title>
</head>
<body>

<h1>Cisco Spark</h1>
<div>Authenticated: <span id="authenticated"></span></div>
<input type="button" value="login" onClick="sparkLogin()">
<input type="button" value="logout" onClick="sparkLogout()">

<div>Call status: <span id="callStatus"></span></div>
<input id="mySparkNummer" value="steven.thonus@infi.nl">
<input type="button" value="call" onClick="sparkCall(getElementById('mySparkNummer').value)">
<input type="button" value="hangup" onClick="sparkHangup()">
<input type="button" value="answer" onClick="answerCall()">
<input type="button" value="reject" onClick="rejectCall()">

<div><video muted id="localMediaStreamUrl" style="border: 1px solid grey; width: 100px; height: 150px;"></video></div>
<div><video id="remoteMediaStreamUrl" style="border: 1px solid grey; width: 300px; height: 450px;"></video></div>


<script src="/assets/spark.js"></script>

<script>
    var call;
    var calling = false;

    function startSpark() {
         console.log('xxxxxxxxxxx starting spark xxxxxxxxxxx');
        loadCache();
        initSpark();
        initListeners();
        authSpark();
         console.log('xxxxxxxxxxx done starting spark xxxxxxxxxxx');
    }

    function loadCache() {
         console.log('loading cached credentials');
        try {
            credentials = JSON.parse(localStorage.getItem('spark-credentials'));
            if (credentials && credentials.refresh_token_expires < Date.now()) {
                credentials = undefined;
            }
             device = JSON.parse(localStorage.getItem('spark-device'));
        }
        catch (error) {
            // ignore
        }
    }

    function initSpark() {

        window.spark = ciscospark;
        const l = window.location;

        Object.assign(ciscospark.config.credentials.oauth, {
            redirect_uri: l.protocol + '//' + l.host + l.pathname
        });

        try {
            Object.assign(ciscospark.credentials.authorization, credentials.authorization);
        }
        catch(error) {
            // ignore
        }
        try {
            ciscospark.device.set(device);
        }
        catch(error) {
            // ignore
        }
    }

    function initListeners() {
        console.log('initializing listeners');

        ciscospark.listenToAndRun(ciscospark, 'change:authorization', function() {
            console.log('got change:authorization');
            localStorage.setItem('spark-credentials', JSON.stringify(ciscospark.credentials));
        });

        ciscospark.listenToAndRun(ciscospark, 'change:device', function() {
            localStorage.setItem('spark-device', JSON.stringify(ciscospark.device));
        });

        ciscospark.listenToAndRun(ciscospark, 'change:credentials', function() {
            console.log('change:credentials: ', JSON.stringify(ciscospark.credentials));
            localStorage.setItem('spark-credentials', JSON.stringify(ciscospark.credentials));
        });

        ciscospark.listenToAndRun(ciscospark, 'change:isAuthenticated', function() {
            console.log('change:isAuthenticated: ', ciscospark.isAuthenticated);
            document.getElementById('authenticated').src = ciscospark.isAuthenticated;
            if (ciscospark.isAuthenticated) {
                ciscospark.phone.register();
                ciscospark.phone.on('call:incoming', function (call) { sparkRing(call); });
            }
        });

        document.getElementById('authenticated').innerHTML = ciscospark.isAuthenticated;
        document.getElementById('callStatus').innerHTML = 'disconnected';
    }

    function authSpark() {
        console.log('starting authentication');
        if (ciscospark.isAuthenticated) {
             console.log(' => authenticated');
            ciscospark.authenticate()
                    .catch(function(reason) {
                        console.error(reason);
                        alert(reason);
                    });
        } else {
            // console.log(' => NOT authenticated');
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    function sparkLogin() {
        ciscospark.authenticate()
                .catch(function(reason) {
                    console.error(reason);
                });
    }

    function sparkLogout() {
        localStorage.removeItem('spark-credentials');
        localStorage.removeItem('spark-device');
//        ciscospark.logout() // IS BROKEN
//                .catch(function(reason) {
//                    console.error(reason);
//                });
    }

    function sparkCall(invitee) {
        console.log('SPARK calling: ', invitee);
        document.getElementById('callStatus').innerHTML = 'calling';
        calling = true; // here to prevent detecting incoming call on making a call
        call = ciscospark.phone.dial(invitee);
        bindCallActions(call);
    }

    function sparkHangup() {
        console.log('hanging up');
        if (call) {
            call.hangup();
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    function sparkRing(new_call) {
        console.log('maybe getting a call. ignoring if calling out myself: ', calling);
        if (!this.calling) {
            console.log('getting a call from ', new_call.from.person.name);
            call = new_call;
            document.getElementById('callStatus').innerHTML = call.status;
            bindCallActions(new_call);
            call.acknowledge();
        }

    }

    function rejectCall() {
        if (call) {
            call.reject();
        }
    }

    function answerCall() {
        if (call) {
            call.answer();
        }
    }
    ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    function bindCallActions(call) {
        call.on('connected', function() { callConnected(call); });
        call.on('disconnected', function() { callDisconnected(call); });
        call.on('change:status', function() { callStatusChanged(call); });
        call.on('remoteMediaStream:change', function() { updateRemoteMedia(call); });
        call.on('localMediaStream:change', function() { updateLocalMedia(call); });
        // not sure if we need this later on:
//        call.on('change:sendingAudio', function() { updateMediaState(call); });
//        call.on('change:receivingAudio', function() { updateMediaState(call); });
//        call.on('change:sendingVideo', function() { updateMediaState(call); });
//        call.on('change:receivingVideo', function() { updateMediaState(call); });
//        call.on('change:localAudioDirection', function() { updateMediaState(call); });
//        call.on('change:localVideoDirection', function() { updateMediaState(call); });
//        call.on('change:remoteAudioDirection', function() { updateMediaState(call); });
//        call.on('change:remoteVideoDirection', function() { updateMediaState(call); });
    }

    function callConnected(new_call) {
        console.log('call connected remoteMediaStreamUrl: ', new_call.remoteMediaStreamUrl);
        console.log('call connected localMediaStreamUrl: ', new_call.localMediaStreamUrl);
        call = new_call
        document.getElementById('localMediaStreamUrl').src = call.localMediaStreamUrl;
        document.getElementById('remoteMediaStreamUrl').src = call.remoteMediaStreamUrl;
    }
    function callDisconnected(new_call) {
        console.log('call disconnected');
        call = new_call
        calling = false;
        document.getElementById('localMediaStreamUrl').src = null;
        document.getElementById('remoteMediaStreamUrl').src = null;
    }
    function callStatusChanged(new_call) {
        console.log('callStatusChanged status: ', new_call.status);
        call = new_call
        document.getElementById('callStatus').innerHTML = call.status;
    }
    function updateRemoteMedia(new_call) {
        console.log('updateRemoteMedia remoteMediaStreamUrl: ', new_call.remoteMediaStreamUrl);
        call = new_call
        document.getElementById('remoteMediaStreamUrl').src = call.remoteMediaStreamUrl;
    }
    function updateLocalMedia(new_call) {
        console.log('updateLocalMedia localMediaStreamUrl: ', new_call.localMediaStreamUrl);
        call = new_call
        document.getElementById('localMediaStreamUrl').src = call.localMediaStreamUrl;
    }
//    function updateMediaState(call) {
//        console.log('updateMediaState: ', call);
//    }

    window.onload = startSpark;
</script>

</body>
</html>

**Comment by Popl7** [comment]
[spark.txt](https://github.com/ciscospark/spark-js-sdk/files/415013/spark.txt)

**Comment by Popl7** [comment]
this is the html page used:
[spark.txt](https://github.com/ciscospark/spark-js-sdk/files/415015/spark.txt)

**Comment by Popl7** [comment]
The quality issue has been resolved. Stupid mistake (ofc)

When the video does not have autoplay, it does work, but the performance is really bad.

The video still only works half in Firefox.
The remote video url gives an error:
------------------------------------------------------------
locus event: locus.participant_joined(unknown)
HTTP "Content-Type" of "text/html" is not supported. Load of media resource http://localhost:5555/undefined failed.c2bcdf01-c610-f4d8-0a75-ba7b0769bf49
Cannot play media. No decoders for requested formats: text/html
------------------------------------------------------------

Local video works fine.
This is both in our app as in the plain html page.
It works fine on Chrome.

**Comment by ianwremmel** [comment]
Ok, I think the problem may have something to do with `http://localhost:5555/undefined`. I think you may be reading the remote url before it's been created. Don't try to set the remote url on your video element until you get the `change:removeMediaStreamUrl` event.

**Comment by Popl7** [comment]
thx Ian, this has fixed the Firefox issue.
