### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jd-carroll** [ciscospark/spark-js-sdk#577]
Looks like no one on the @spark-js-sdk team uses a Windows machine...

The following lines make it impossible to run `npm install` on a windows machine:
```
    "prepublish": "in-install && npm run --silent link-lint-rules || not-in-install",
    "link-lint-rules": "rm -rf ./node_modules/@ciscospark/eslint-config & mkdir -p node_modules/@ciscospark && ln -s $(pwd)/packages/node_modules/@ciscospark/eslint-config $(pwd)/node_modules/@ciscospark/eslint-config",
```

_There is no `rm` on the windows command line and if you tell windows to `mkdir -p ...` it will make a directory named "-p"_

Any chance this could be moved into a gulp task so that it is portable across OS platforms?

**Comment by ianwremmel** [comment]
We're in the process of moving everything to npm scripts (we don't use gulp, but we're working to get rid of grunt). We'll make sure to take care of this as part of that process.

**Comment by ianwremmel** [comment]
@jd-carroll with the release of 0.8.0, I'm reasonably confident that all scripts should be platform agnostic. If you run into any additional issues, feel free to reopen. 

Also note that the best way to *use* this sdk is by installing it from npm via `npm install ciscospark`. Cloning from git is recommended only for those intent on submitting pull requests.

**Comment by gbrodz** [comment]
@ianwremmel  thanks. 

Question for you: has this platform agnostic change been made to the accompanying spark-js-sdk-example depot?  How about the react-ciscospark one?

I can log this issue/question on those as well but wanted to ask you while we were on this same thread.

Thanks

**Comment by ianwremmel** [comment]
To the best of my knowledge, react-ciscospark is already setup this way. I believe the example repo is still very bash-centric.

Sent from my iPhone

On May 16, 2017, at 7:11 AM, gbrodz <notifications@github.com<mailto:notifications@github.com>> wrote:


@ianwremmel<https://github.com/ianwremmel> thanks.

Question for you: has this platform agnostic change been made to the accompanying spark-js-sdk-example depot? How about the react-ciscospark one?

I can log this issue/question on those as well but wanted to ask you while we were on this same thread.

Thanks

-

**Comment by adamweeks** [comment]
@gbrodz we've attempted to make the `react-ciscospark` repo cross platform by changing our scripts to use the `cross-env` package. If you find where something does not work on Windows, please open an issue and we will get it fixed!

**Comment by jd-carroll** [comment]
awesome, thanks guys this is working great!!
