### ISSUE TITLE
determineService Error : https://idbroker.webex.com/idb/oauth2/v1/access_token does not reflect a known service

### ISSUE THREAD

**Issue by tshmukle** [ciscospark/spark-js-sdk#588]
Using sdk to create KMS keys, resources and make authorization requests. It is a node application the runs in browser , doing multiple redirects. Once ciscospark object is created using constructor (see the code example below), we do see the following error in debugger:
===========
determineService: function determineService(url)
called with url="https://idbroker.webex.com/idb/oauth2/v1/access_token"
Error: https://idbroker.webex.com/idb/oauth2/v1/access_token does not reflect a known service
at child.determineService (https://localhost:8000/ui/app.js:153514:38)
at https://localhost:8000/ui/app.js:113576:37
at <anonymous>
==========
This error seems benign , since we still can continue with getting KMS keys, resources and authorizing.
Our code example:
require('@ciscospark/plugin-encryption');
const CiscoSpark = require('@ciscospark/spark-core').default;
....
const spark = new CiscoSpark({
			  credentials: {
			    authorization: kmsToken
			  },
              config: {
				credentials: {
					client_id: clientId
				}
			}
			});
spark.encryption.kms.createUnboundKeys({count: 1})
			  .then(function (keys) {
                debugger;
			    var key = keys[0];
			  })
			  .catch((err) => {
			    console.error(err);
			  });

**Comment by ianwremmel** [comment]
I believe this is fixed. Please open a new issue if you find otherwise.
