### ISSUE TITLE
API Reference docs missing?

### ISSUE THREAD

**Issue by patricksmith** [ciscospark/spark-js-sdk#642]
Attempting to view the API reference section of the docs website (https://ciscospark.github.io/spark-js-sdk/api/) currently results in a mostly empty page with no reference docs:

![image](https://user-images.githubusercontent.com/1062277/27879662-5d959b0a-6190-11e7-9af8-b0c26fe18d6e.png)

**Comment by bbender** [comment]
@patricksmith, thanks for pointing this out. It's fixed now.
