### ISSUE TITLE
people.get("me")  no longer works

### ISSUE THREAD

**Issue by marchfederico** [ciscospark/spark-js-sdk#676]
when using the ciscospark nodejs lib people.get("me") no longer works.  This has broken the botkit library.

The problem is in the @ciscospark module.

https://github.com/ciscospark/spark-js-sdk/blob/master/packages/node_modules/%40ciscospark/plugin-people/src/people-batcher.js#L69

Should be:

resource: `people/${ids}`

Also the handleHttpSuccess function should check to see if there are items...because the get("me") will not return an array of items.

**Comment by adamweeks** [comment]
@marchfederico didn't realize this was even possible! I've added specific support for it in PR #678
