### ISSUE TITLE
Retrieving authorization objects on KRO never comes back if there are a lot of those

### ISSUE THREAD

**Issue by tshmukle** [ciscospark/spark-js-sdk#749]
This issue is some what a continuation of "Heap out of memory issue in KMS library: https://github.com/ciscospark/spark-js-sdk/issues/747"
When call internal.encryption.kms.listAuthorizations({kroUri: resourceUri}) on a resource with a LOT of authorization objects, the request hangs forever and never come back with either results or error.
Please note, for that to happen we had to locally fix KMS sdk client lib error handling problem described in the issue "Heap out of memory issue in KMS library: https://github.com/ciscospark/spark-js-sdk/issues/747"
The same call works fine when we have 4-10 authorization, It fails if ~100.
Once I locally quickly fixed the exception that brings the app info an infinite loop issue and memory problem:
kms: wrapping ephemeral key request
kms: request error TypeError: Cannot read property 'requestId' of undefined
    at KMSRequest.wrap (/Users/huichen/hui_dev/onboarding/app/node_modules/node-kms/lib/request.js:88:43)
    at /Users/huichen/hui_dev/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms.js:406:18
    at process._tickCallback (internal/process/next_tick.js:109:7)
by simply changing the code below :
=========================================
 // set the requestId if not already set
  if (!this.requestId || opts.requestId) {
    this.requestId = opts.requestId || ctx.requestId();
  }
====================================
changed to :
 // set the requestId if not already set
  if (!this.requestId || opts.requestId) {
    if (opts) {
      this.requestId = opts.requestId;
    } else if (ctx)
      this.requestId = ctx.requestId();
  }
================================
then we can see the actual issue with timeout for the request on a client side + slow request response from KMS server. I am not sure if this has to be fixed in KMS server (faster queries ??? ) , as well as on a client (kms lib), so it will stop retrying after some number of timeout errors , because currently it keeps re-trying the request forever and gets the timeout error as below, so our REST call on a server nodejs app that uses kms lib (CCFS) ,  never returns:
============================
/**********************************************************************\ 
Request: POST https://encryption-a.wbx2.com/encryption/api/v1/kms/messages
WEBEX_TRACKINGID:  spark-js-sdk_87c1881a-deee-4592-9969-d62b2ea563c3_42
timestamp (start):  1510770959087 2017-11-15T18:35:59.087Z
Request Options: { method: 'POST',
  service: 'encryption',
  resource: '/kms/messages',
  body: 
   { destination: 'https://encryption-a.wbx2.com/encryption/api/v1',
     kmsMessages: 
      [ 'eyJhbGciOiJkaXIiLCJraWQiOiJodHRwczovL2VuY3J5cHRpb24tYS53YngyLmNvbS9lbmNyeXB0aW9uL2FwaS92MS9lY2RoZS80OTMyMDJjZC1mNTY2LTRkZTQtOTc0Yy1iNDZjZDdhMjg4NDIiLCJlbmMiOiJBMjU2R0NNIn0..W33ik7P02oV3e5Y-.gA5wYQd19euVerZMfcACKM2LnfoHJf0bzCASfFj0ZWcIFv1ojC9LFbPtfBBIQbjs2aOGgzIj8PEp9u5vuuV_ulUa2or5B9BhPVnEk0T9Ag-CRWB8tQdlSbIkiTZuI7tCvAr41DW3s1z3JjrfJ4sgj91xE5ZXiIQXMPq2UwZtneeuPvdQGvLoodnMKvDQ9ycav147XNYenrkNpJ-2w0gu83MOEv9YpXU4zyMMVcdc_1-_0DOoWTkB-Yzuw15q_zFpLHU-fD_5gPK0EeLKtWQF1PmHXx_GZ8JtejxG9YuLpN6SenHu996E2Q84FymiJsqJxTt9cx-6V2p4orb2IeJKiGMUzHlz9V2cdyOQntK2F_0XlnikTTyvqwl38ZBHtm6Eq9r97eah7ckHgIEW1SCQGbEKwhd26yXReyVhR04dvLqNGljmYXZhLC7laMCnyISq3l_ubvF5lI_OR1Fd7volU2UA5ZcVUBr4WXkWOwCSPid-xDlCXtB73RBQzwGUe4ucabj1SvddwSqrV9M38LeK2RYiPBA-SunqopNOHCUZEBkVPSyY0vLW6mbG40ObJHIahZJfoqHH-nXLZ6uwmO-ecuUqaAHxiMPf3cBTFuEgpLXi8EmJ5OmW0e6kKlF9PMLdNHpm93R2o29KlZFa2mboofJjcgHK0aBGK9z2jPC-TJH2vTGgkjEvJiVOxeSrsXF4fC34Bf6akBD76WgbRI-0UHeB-X47GJw330WhEocdhV4JLpdNxW-UFTTtp5f1pwzyLQHXxgdFyHp7DbEL1guhVKJT_fN24duIUgU4fXHLbtvpmeO0T18_643A7FAhWvVYsv8_dxLXnHnX0i7Rh3LIG3-QMwbghPCEWSSByVMi7g-i_fTrrSptbitXEtNh5hALagCVQmpED_GZHutB4d3txVXI0o0CP22wV94pdGd-cU0cNyOZzPWBl9EeXKryugWkga5wd29bfYtznehrtr_X_XuM8td8_sLRI2e2z3Br_MO5sAvdfsy13QedS75wmz3UJQ3LTxlVbRb7QWIXCO_Oj5oPZF-NVeO_sAifrJLKWM-PDWKLcC73pKhkeN-BbEQ0F5n7mV38ly47LlBfjNqgOlpONDUT1Xmc8SFJf47aDdyE0H6H7l5sogmSxkTthJXGR2zRg49-M0b1tBHsfVvB_jd0MpUTTWyUx-KFDpGwF3pzcmHZ0eEgH9E37OJlazB2Ct200p7G6Dd5CijD-eveCy6xrvEp-j1fXskr9_HKYEdGl1HwAvfrtnHQ51xwAazgWoF1E0DkYOsnFT_WXqv4u3_vhAsCLYcrJPKsfcggPreewRDtESGnJvzsSwjhht_GZzm412sCVaQz5TKcpN3SJufn1Av9heYvuRdh65JK7r0a7BnwKt96JlgQeOmCDkdW9zwn6f_JP6f2FQRDs2tzf5xnDXoWQ93Lxtqf7NO83jsPrhCg6YMtyUungOuYErdY06Luk_QSFDUwveXqQgAUFVmS1fy9k8FQE5N7kNAi5mHk_0xTUqH4my0_bsUHasINZDwM9YKuzqrFHk0lOW_zl_oZH3D8lSaB6hj5-LNK5YYOqzLylhwiIjD7FKqezvlSKAhq6t5zktCRD2nd2poM5fWly95qUclvc-34nZ-nUdaMCyETUSQgUCmdkwzMLixU2b6HP_I4HXDFK8Yh30t_Oh6ruPUBwr-FMix2UEOdPygubvYe4unEtzyfv1BhLiAi6Sr6-ib3mZomiTQjdj0RRWMe9VhJgmAfm1XQWepENeP5dVNnmGuEZPtuR269k0i3WBv8l9GpYVKpLxdMa_lXAh1_8d3Y99Ufap4XhE3N5PSx5d456GlvgoY95Muu0gYT_h-nXi5VwaXyCMKukLPmMVoYfIxDXauV67L1P-H9M55X3wwLAoVlFLsIwxSzvzPglyqDmnTPamS8Z33u8BaToBdHFECfF7LirrxG0fEb7U3F402xcfaJg-UkENxdy6NtYLBGEDUQb0IPWrkG1HwiFz_AZtlWkccKC1B2U8f8iDmx-mhxWLI0zX66eRCxkJgZ-yG9SRMzeSMxMRH-BgkvD10S7DEnyesBztqHRrxjM_UwZGjqMMf_XivukMKbU75C-0n7bvQfamR45gRqln5g-5blBC0MTzb9TMcEzYX_YVzk3uPhJWv3NWHhXlPM8XLyNfvlrolDPU-QALhmO0zXeb9ndyi9PrIvGtjiLNay27XBz_GeYmdrufFKpeS42wTEHge7tX8tQRC4YHCFNW49N2sgzNxGkPe2JoIZs1usdAPpONHtZ48hBFNrJ7URKZWEaCdVWQOGb1sU6mhsCSZsLeaUdcUDCdXu__L3AD0OVV03uNQE77ps7FDc-6riUUcANlureb4YTntwyPKow2Azup-e4Tpkd3SjcxxLxYbeLi_l5q_x175SrTnulZUSg2d-Mszl9voBF2l6rv-H99hd3nYjanP_yGcssa7j6cSf8JhKxaa_vstW7HWaMP_6XNljQ81kY7f9Y4EqrJyf_9tQHTs.Q3ORbsIeT0NLLVCH8fwkAw' ] },
  json: true,
  headers: 
   { 'user-agent': '@ciscospark/http-core',
     trackingid: 'spark-js-sdk_87c1881a-deee-4592-9969-d62b2ea563c3_42',
     'spark-user-agent': 'spark-js-sdk/1.14.3 (node)',
     authorization: 'Bearer eyJhbGciOiJSUzI1NiJ9.eyJleHBpcnlfdGltZSI6MTUxMDc5MDgzNjgzMiwidXNlcl90eXBlIjoidXNlciIsInJlYWxtIjoiOGI1OTNhYTMtYmVjNS00MzgzLThlY2ItNTIyMWVmZGEyNmUyIiwiY2lzX3V1aWQiOiI3NmI2MGRhNC0wNTYxLTQ4MmUtODBlNC1kMGNkMGVlMjdmMWUiLCJyZWZlcmVuY2VfaWQiOiJjZGY0MDkzZi1kZjBmLTQ0N2ItYWE2Ni0xZGQzOGJjZjRiZjciLCJpc3MiOiJodHRwczpcL1wvaWRicm9rZXIud2ViZXguY29tXC9pZGIiLCJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiY2xpZW50X2lkIjoiQzExZDdkMWU2YWE0Y2Y5YjU0ODcxZGRkZWE5ZDk5NTgwYzNhM2UxMjA0YWRjODcxZmM5MGU4Y2I1M2Y2ZDU0MDMiLCJ0b2tlbl9pZCI6IkFhWjNyMFlXRmpNREJoTkdJdE9EVTFaaTAwWXpBNExUazVPRFV0WVRreE5HTXdOMlF6TWpsbFlqQm1OelF3T0RNdFpESTIiLCJwcml2YXRlIjoiZXlKaGJHY2lPaUprYVhJaUxDSmpkSGtpT2lKS1YxUWlMQ0psYm1NaU9pSkJNVEk0UTBKRExVaFRNalUySW4wLi5Gd0tQYmJaVnNzNkZIRFZzdk9penBnLnZEZzFFZEE2WXU3SUhqTThpc2RFTFVfM3BxdTJ5VW9yazF0aktHZXl4OEJYZGpzUTJkVE5yZnNYQUhHVjZneW5vUXg1WTdBME10ZUI2ak10V3g4NVM3VWNQR1ZnMlJhTUtFbGNjSGx3VEFYQld3YjZxSDBfNVlNNTJwYjRFelNVZF9tUW5DbFhfQkJWV2Z0ZDFRS1BWTmZrVTd0SDU5cWI2Skdma3BkRDRxZm5aNHBhX0tzdlRHSHBxWnk4LU5VQVBLRE1wQ0szRFVqVFdxYzhPQmVJQUxMSUVScXFoSWlCWERteHVYTHlzeUI5NlZzTXRERTdPN0JTMGZybWtjMmc5ZXpCczRSSW9xVm9jQllZZl9HTlVMSDY1SktYcXRPY3pkZEZsaWw3RlBZMmI3UVFIdWs1d2RpRUU3ZXBPQkVWaWZIcUgwczhka21pMU81Uko2X0hqbTlpSzRxWjF1VkYwZWpNemp3UWs0Ti1CeklMbng5UkhWQ0pyT1NPSkVORU9sWkFkUXNMMmdNOFF5OTBlRGdoSjhVOFFXOFhXNG5WLUd4NERHQUNhbnpENTNoM1c3NnNWSDcyOG51QVRyMkRMaGpXVG5VYUhaLUctQ3lRV0dNTFVRLjI5aUNFcVMwMGxoLXdNeXUtdEFaSEEiLCJ1c2VyX21vZGlmeV90aW1lc3RhbXAiOiIyMDE3MTExMDA2NDcxMi4yOTdaIn0.cVWkfWBnKIpZXUYXUV1d4ywaM23Sk06qHyMtB1MJ4Ns_BYQ30Mmt9zDxHaffL8mWdAG4WQBZ7bwu_Unb8YvbzRTRuKELHPzESKPMOaCb-CSI49swAcYAw1Dyyis2n4QhnshqFjk_xVg_uAZuYQBzV-GRTPdwtTlnwTt51qUu-jS5quCvo8SKfl4JjtRde1lQv-_s1uT53UM5gx63n3dWNVAg3f3y3ambK1hFGEOz81AGyQ1eKriK78sGzMoUMlMB-1uniFaUKfGAbCvkkQd1778xeYyJUYFXMXMWV-Q0weNKPhSBqXrG8iG1hMG3_pvTVJ2uiSXKJe1R3cbCBx7GcA',
     'cisco-no-http-redirect': true,
     'cisco-device-url': 'https://wdm-a.wbx2.com/wdm/api/v1/devices/0f6026e0-9dc0-4681-ade1-2fe3aeb935e9' },
  '$timings': { requestStart: 1510770959086, networkStart: 1510770959087 },
  uri: 'https://encryption-a.wbx2.com/encryption/api/v1/kms/messages',
  '$redirectCount': 0 }
Status Code: 202
WEBEX_TRACKINGID: spark-js-sdk_cd06ec6a-bd3d-4508-babc-d9c7db1f5af2_53
Network duration: 221
Processing duration: 221
timestamp (end):  1510770959157 2017-11-15T18:35:59.157Z
\**********************************************************************/
Status Code: 202
WEBEX_TRACKINGID: spark-js-sdk_87c1881a-deee-4592-9969-d62b2ea563c3_42
Network duration: 216
Processing duration: 217
timestamp (end):  1510770959303 2017-11-15T18:35:59.303Z
\**********************************************************************/
socket: ping 408e5ceb-780e-425e-a976-bc8a3bf73272
socket: ping fdf4c188-c9f2-4f4f-a555-648eee561e93
kms: request timed out; request id: ; timeout: 6000
kms: request error KmsError: An error was received while communicating with the KMS
    at KmsError.ExtendableBuiltin (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:50:44)
    at KmsError.Exception (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:97:142)
    at new KmsError (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-errors.js:54:123)
    at /Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-batcher.js:161:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
mercury: already connected, will not connect again
kms: request error KmsError: An error was received while communicating with the KMS
    at KmsError.ExtendableBuiltin (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:50:44)
    at KmsError.Exception (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:97:142)
    at new KmsError (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-errors.js:54:123)
    at /Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-batcher.js:161:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
one flight: attempted to invoke connect while previous invocation still in flight
kms: request error KmsError: An error was received while communicating with the KMS
    at KmsError.ExtendableBuiltin (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:50:44)
    at KmsError.Exception (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/common/dist/exception.js:97:142)
    at new KmsError (/Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-errors.js:54:123)
    at /Users/tshmukle/cloud/onboarding/app/node_modules/@ciscospark/internal-plugin-encryption/dist/kms-batcher.js:161:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by tshmukle** [comment]
Forgot to mention that I have tried this with different nodejs versions just to make sure  - see the same problem with the latest node release version v8.9.1 , as well as latest available v.9.x

**Comment by ianwremmel** [comment]
It's really hard to tell with the current formatting, but I think this is probably also related to #747 and fixed by #740

**Comment by ianwremmel** [comment]
I believe this is fixed by #740. Please open a new issue if you find otherwise.
