### ISSUE TITLE
web-client forces logout on public network even while the user is actively reading new messages

### ISSUE THREAD

**Issue by saurjai3** [ciscospark/spark-js-sdk#756]
web-client is forcing logout on public network even while the user is actively reading new messages. This is causing user frustration.

Steps to Reproduce:
1. Login on Spark web-client on a public network
2. Keep using the web-client to read new messages and do not post any new message.
3. After 30 mins the client forces logout.

Expected Behavior:
The user should be considered as active while reading the new messages(i.e while sending acks), and hence it should not force logout. Currently the reset timer works if the user posts a message but not if he is just reading messages.

Suggested fix:
Remove the check for activity.verb !== `acknowledge` in internal-plugin-conversation/src/conversation.js
![01_49_23](https://user-images.githubusercontent.com/22205801/33099029-4384fd5e-cec4-11e7-9cb8-50a2293d5121.jpg)

**Comment by ianwremmel** [comment]
Please check with @mwegman or the original designers of the feature, and assuming there's no good reason for the ack check, PR is very welcome :)

**Comment by mwegman** [comment]
You can remove the check. I have no idea why that is there. Sending an ACK shows the user is interacting with the client and should reset the timer.

**Comment by ianwremmel** [comment]
I vaguely remember wanting to exclude it in case it would be too easy to send automatically, but yea, at this point, i have no objections to removing it.

**Comment by aimeex3** [comment]
is this completed or does there need to be more investigation? https://github.com/ciscospark/spark-js-sdk/pull/759/files is merged

**Comment by saurjai3** [comment]
Hi Aimee
It is already merged and updated in web-client as well.
