### ISSUE TITLE
 Leave Conversation API failing 

### ISSUE THREAD

**Issue by SharikSaigal** [ciscospark/spark-js-sdk#765]
Hi ,
	I am from spark care team and we use  spark-js-sdk @ciscospark/internal-plugin-conversation for spark conversation activities .Have observed 
  Leave Conversation API (this.ciscoSpark.internal.conversation.leave)failing with 502 Http Response  from last week even after upgrading SDK to latest version 1.19.4.

Request URL:https://conv-a.wbx2.com/conversation/api/v1/activities?personRefresh=true
Request Method:POST
Request Payload:
{  
   "target":{  
      "id":"b5fd7930-d41c-11e7-8cf8-db3d18f12957",
      "objectType":"conversation",
      "url":"https://conv-a.wbx2.com/conversation/api/v1/conversations/b5fd7930-d41c-11e7-8cf8-db3d18f12957",
      "activities":{  
         "items":[  

         ]
      },
      "participants":{  
         "items":[  

         ]
      }
   },
   "verb":"leave",
   "objectType":"activity",
   "clientTempId":"20cf734c-cbc7-4108-8f2f-a49cd9159a23",
   "actor":{  
      "objectType":"person",
      "id":"3711639d-5dfe-430f-a588-ab384b0860a9",
      "entryUUID":"3711639d-5dfe-430f-a588-ab384b0860a9"
   },
   "object":{  
      "id":"3711639d-5dfe-430f-a588-ab384b0860a9",
      "objectType":"person",
      "entryUUID":"3711639d-5dfe-430f-a588-ab384b0860a9"
   }
}

Status Code:502 

{  
   "message":"Error executing request (url = kms://ciscospark.com/keys/89d6280a-559d-4413-b8d7-daebc1c5c79a - trackingId: spark-care-desktop_93b4f180-43b5-4903-b535-997eb938adba_13)",
   "errors":[  
      {  
         "description":"Error executing request (url = kms://ciscospark.com/keys/89d6280a-559d-4413-b8d7-daebc1c5c79a - trackingId: spark-care-desktop_93b4f180-43b5-4903-b535-997eb938adba_13)"
      }
   ],
   "trackingId":"spark-care-desktop_93b4f180-43b5-4903-b535-997eb938adba_13"
}

Can you kindly help.

**Comment by ianwremmel** [comment]
See https://github.com/ciscospark/spark-js-sdk/issues/768 for more details. The sdk should be doing more to warn you. that said, the most performant fix will be to change your application code to pass more complete conversation objects conersation methods.

**Comment by SharikSaigal** [comment]
Thanks @ianwremmel  passing the complete conversation object solved the issue.
