### ISSUE TITLE
Improve Documentation (Authentication)

### ISSUE THREAD

**Issue by tahanson-cisco** [ciscospark/spark-js-sdk#81]
Maybe it’s obvious for Node folks, but I don't think its common sense for most.  In order to get my code to pass authentication and working, I needed the following lines, which don’t definitively appear anywhere:

var assert = require('assert');
process.env['CISCOSPARK_ACCESS_TOKEN'] = 'MY_ACCESS_TOKEN';
assert(process.env.CISCOSPARK_ACCESS_TOKEN);
var ciscospark = require('ciscospark/es5');

Can some of the examples include a little more beyond or prior to:
var ciscospark = require('../..');

**Comment by ianwremmel** [comment]
Hi @tahanson-cisco, there's work in progress to improve the docs. Where did you find `var ciscospark = require('ciscospark/es5');`? I was pretty sure I eliminated that from all of the docs over a month ago.

The getting started guide (linked at the top of the github repo) cover setting one's access token via environment variables; those steps were left out of the individual examples to avoid aggressive repetition, but I'll definitely work to make the examples clearer.

**Comment by tahanson-cisco** [comment]
var ciscospark = require('ciscospark/es5'); Was just what I used to get it to work, not found anywhere.  I wasn't sure what else to use.

Sorry, I didn't realize that link was to a getting started guide.  Totally missed that.  Anyway to make it a bit more obvious, or is that standard?  It seems pretty easy to miss since it isn't labeled.

**Comment by ianwremmel** [comment]
Closing as new documentation has been released.
