### ISSUE TITLE
Spark Care: Call.answer() is not working with chrome 64

### ISSUE THREAD

**Issue by sonbansa** [ciscospark/spark-js-sdk#820]
## Expected Behavior

call.answer() should no throw exception with ciscospark v1.10.0 and chrome v64

## Current Behavior

Spark Care uses v1.10.0 for ciscospark, and chrome 64. When trying to make call, using call.answer(), It gives following error: DOMException: Failed to execute 'addTrack' on 'RTCPeerConnection': A sender already exists for the track.
However it is working with chrome v63

## Possible Solution (we welcome any logical suggestion)

One solution is to upgrade spark js sdk to latest version, but for that, we have to add enableExperimentalGroupCallingSupport: true in our configuration. So, we want to check how much can we rely on this, as we use multi party calling. 
## Environment Details

* SDK Version v1.10.0
* Node/Browser Version 6.10.0
* NPM Version

**Comment by ianwremmel** [comment]
Chrome 64 requires an updated version of webrtc-adapter. Updating to the lastest sdk is the only available solution. If you weren't setting `enableExperimentalGroupCallingSupport`, I'm not sure why it would be necessary now, but, you should definitely move to it as soon as possible.
