### ISSUE TITLE
default install of modules should not install mmmagick 0.3.16

### ISSUE THREAD

**Issue by glhewett** [ciscospark/spark-js-sdk#84]
After cloning and installing node modules, the unit tests did not pass.  The fetchFixture function for node did not work and `Util image` tests failed.

I was able to fix the tests reverting the version of mmmagick to 0.3.15.  This issue recommends that we lock the version of mmmagick to 0.3.15.

### To see tests fail

```sh
npm i mmmagic@0.3.16 
grunt test:unit
```

### To fix tests after installing 0.3.16

```sh
npm i mmmagic@0.3.15
grunt test:unit
```

**Comment by tran2** [comment]
I have no issue with mmmagic@0.3.16

**Comment by glhewett** [comment]
I have reinstalled graphicsmagic with more options, and it seems to be working for me.  I am not sure which option was the key or if the rebuild in general was the key.  I would be happy to dig into the specific if other begin having issues.

```
brew reinstall graphicsmagick --with-webp --with-libwmf --with-ghostscript
```

@ianwremmel, I recommend this issue be closed.

**Comment by ianwremmel** [comment]
sounds good. it seems the pipeline has actually be one 0.3.16 for a while, so i think it was something environmental on your machine. Will close for now. Thanks for digging into it!
